### ISSUE TITLE
FRED | COVID-19 Economic Data Tracking Datasets

### ISSUE THREAD

**Issue by derekwolpert** [rearc-data/adx-status-page#11]
Series featured in [FRED's COVID-19 Economic Data Tracking dashboard](https://research.stlouisfed.org/dashboard/49765)

| Name | URL |
|-|-|
| Initial Claims | https://fred.stlouisfed.org/series/ICSA |
| Indexes of Aggregate Weekly Hours of All Employees, Total Private | https://fred.stlouisfed.org/series/AWHAE |
| All Employees, Total Nonfarm | https://fred.stlouisfed.org/series/PAYEMS |
| Unemployment Rate | https://fred.stlouisfed.org/series/UNRATE |
| Advance Real Retail and Food Services Sales | https://fred.stlouisfed.org/series/RRSFS |
| Consumer Price Index for All Urban Consumers: All Items in U.S. City Average | https://fred.stlouisfed.org/series/CPIAUCSL |
| Industrial Production Index | https://fred.stlouisfed.org/series/INDPRO |
| Real Disposable Personal Income | https://fred.stlouisfed.org/series/DSPIC96 |
| Real Gross Domestic Product | https://fred.stlouisfed.org/series/GDPC1 |
| Real-time Sahm Rule Recession Indicator | https://fred.stlouisfed.org/series/SAHMREALTIME |
| Smoothed U.S. Recession Probabilities | https://fred.stlouisfed.org/series/RECPROUSM156N |
| Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma | https://fred.stlouisfed.org/series/DCOILWTICO |
| Housing Starts: Total: New Privately Owned Housing Units Started | https://fred.stlouisfed.org/series/HOUST |
| Total Business Inventories | https://fred.stlouisfed.org/series/BUSINV |
| Advance Real Retail and Food Services Sales | https://fred.stlouisfed.org/series/RRSFS |
| Light Weight Vehicle Sales: Autos and Light Trucks | https://fred.stlouisfed.org/series/ALTSALES |
| Value of Manufacturers' Shipments for Capital Goods: Nondefense Capital Goods Excluding Aircraft Industries | https://fred.stlouisfed.org/series/ANXAVS |
| Manufacturers' New Orders: Nondefense Capital Goods Excluding Aircraft | https://fred.stlouisfed.org/series/NEWORDER |
| University of Michigan: Consumer Sentiment | https://fred.stlouisfed.org/series/UMCSENT |

**Comment by AyushSVarma** [comment]
Initial Claims: [https://github.com/rearc-data/fred-initial-claims](https://github.com/rearc-data/fred-initial-claims)

Indexes of Aggregate Weekly Hours of All Employees, Total Private: [https://github.com/rearc-data/fred-weekly-hours-employees](https://github.com/rearc-data/fred-weekly-hours-employees)

All Employees, Total Nonfarm: [https://github.com/rearc-data/fred-employees-total-nonfarm](https://github.com/rearc-data/fred-employees-total-nonfarm)

Unemployment Rate: [https://github.com/rearc-data/fred-unemployment-rate](https://github.com/rearc-data/fred-unemployment-rate)

Advance Real Retail and Food Services Sales: [https://github.com/rearc-data/fred-retail-food-sales](https://github.com/rearc-data/fred-retail-food-sales)

Consumer Price Index for All Urban Consumers: All Items in U.S. City Average: [https://github.com/rearc-data/fred-consumer-price-index](https://github.com/rearc-data/fred-consumer-price-index)

Industrial Production Index: [https://github.com/rearc-data/fred-industrial-production-index](https://github.com/rearc-data/fred-industrial-production-index)

Real Disposable Personal Income: [https://github.com/rearc-data/fred-real-disposable-personal-income](https://github.com/rearc-data/fred-real-disposable-personal-income)

Real Gross Domestic Product: [https://github.com/rearc-data/fred-real-gross-domestic-product](https://github.com/rearc-data/fred-real-gross-domestic-product)

Real-time Sahm Rule Recession Indicator: [https://github.com/rearc-data/fred-real-time-sahm-rule](https://github.com/rearc-data/fred-real-time-sahm-rule)

Smoothed U.S. Recession Probabilities: [https://github.com/rearc-data/fred-smoothed-recession-probabilities](https://github.com/rearc-data/fred-smoothed-recession-probabilities)

Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma: [https://github.com/rearc-data/fred-crude-oil-prices](https://github.com/rearc-data/fred-crude-oil-prices)

Housing Starts: Total: New Privately Owned Housing Units Started: [https://github.com/rearc-data/fred-privately-owned-housing](https://github.com/rearc-data/fred-privately-owned-housing)

Total Business Inventories: [https://github.com/rearc-data/fred-total-business-inventories](https://github.com/rearc-data/fred-total-business-inventories)

Advance Real Retail and Food Services Sales: [https://github.com/rearc-data/fred-retail-food-sales](https://github.com/rearc-data/fred-retail-food-sales)

Light Weight Vehicle Sales: Autos and Light Trucks: [https://github.com/rearc-data/fred-light-weight-vehicle-sales](https://github.com/rearc-data/fred-light-weight-vehicle-sales)

Value of Manufacturers' Shipments for Capital Goods: Nondefense Capital Goods Excluding Aircraft Industries: [https://github.com/rearc-data/fred-value-of-shipments](https://github.com/rearc-data/fred-value-of-shipments)

Manufacturers' New Orders: Nondefense Capital Goods Excluding Aircraft: [https://github.com/rearc-data/fred-nondefense-capital-goods](https://github.com/rearc-data/fred-nondefense-capital-goods)

University of Michigan: Consumer Sentiment: [https://github.com/rearc-data/fred-umichigan-consumer-sentiment](https://github.com/rearc-data/fred-umichigan-consumer-sentiment)
