### ISSUE TITLE
MIT Election Data and Science Lab

### ISSUE THREAD

**Issue by derekwolpert** [rearc-data/adx-status-page#12]
https://electionlab.mit.edu/data

In addition to the links below, there are possible valuable datasets on [MEDSL's GitHub Account](https://github.com/MEDSL).

| Name | URL |
|-|-|
| Local Precinct-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/Q8OHRS |
| State Precinct-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GSZG1O |
| State Office-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XSOFHD |
| U.S. President Precinct-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LYWX3D |
| U.S. House of Representatives Precinct-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PSKDUJ |
| U.S. Senate Precinct-Level Returns 2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NLTQAD |
| County Presidential Election Returns 2000-2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VOQCHQ |
| U.S. House 1976–2018 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2 |
| U.S. President 1976–2016 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX |
| U.S. Senate 1976–2018 | https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PEJ5QU |

**Comment by AyushSVarma** [comment]
[Local Precinct-Level Returns 2016](https://github.com/rearc-data/mit-local-precinct-levels-2016)

[State Precinct-Level Returns 2016](https://github.com/rearc-data/mit-state-precinct-level-returns-2016)

[State Office-Level Returns 2016](https://github.com/rearc-data/mit-state-office-level-returns-2016)

[U.S. President Precinct-Level Returns 2016](https://github.com/rearc-data/mit-president-precinct-level-returns-2016)

[U.S. House of Representatives Precinct-Level Returns 2016](https://github.com/rearc-data/mit-us-hor-precinct-level-returns-2016)

[U.S. Senate Precinct-Level Returns 2016](https://github.com/rearc-data/mit-senate-precinct-level-returns-2016)

[County Presidential Election Returns 2000-2016](https://github.com/rearc-data/mit-county-presidential-2000-2016)

[U.S. House 1976–2018](https://github.com/rearc-data/mit-us-house-1976-2018)

[U.S. President 1976–2016](https://github.com/rearc-data/mit-us-president-1976-2016)

[U.S. Senate 1976–2018](https://github.com/rearc-data/mit-us-senate-1976-2018)
